package org.omg.PortableServer;


/**
* org/omg/PortableServer/IMPLICIT_ACTIVATION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/ojdkbuild/lookaside/java-1.8.0-openjdk/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, April 23, 2019 6:09:21 AM PDT
*/

public interface IMPLICIT_ACTIVATION_POLICY_ID
{

  /**
	 * The value representing IMPLICIT_ACTIVATION_POLICY_ID.
	 */
  public static final int value = (int)(20L);
}
