package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/HOLDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/ojdkbuild/lookaside/java-1.8.0-openjdk/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, April 23, 2019 6:09:19 AM PDT
*/

public interface HOLDING
{

  /** Object adapter state that holds requests temporarily until the 
   * state is changed.
   */
  public static final short value = (short)(0);
}
